[tox]
envlist = py37,py38,py39,py310,py311
skip_missing_interpreters = true

[testenv]
deps =
    pytest>=6.0
    pytest-cov>=2.10.0
commands = pytest false_feet_algorithm/tests/ -v --cov=false_feet_algorithm

[testenv:lint]
deps = black mypy
commands =
    black false_feet_algorithm --check
    mypy false_feet_algorithm

[testenv:format]
deps = black
commands = black false_feet_algorithm
